export const teacherWebhooks: Record<string, string> = {
	김민정:
		'https://chat.googleapis.com/v1/spaces/AAQAP9WjC-o/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=0ernJwOL7BSceQ32yW192kXFl3G_e1Ce_lt6U58KgxU',
	전태상:
		'https://chat.googleapis.com/v1/spaces/AAQA4PQ551k/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=M3Bfv44ngYV1vZ89DbkZWqg-YGUTleumvsFkZzD646g',
	김보미:
		'https://chat.googleapis.com/v1/spaces/AAQA7dyDPcg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=UOqAa-MH01oJySF04Pey5ENdTQJjGBfqD7d-BoeZRvk',
	김유진:
		'https://chat.googleapis.com/v1/spaces/AAQAdT5MU0E/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=13QMsJ9rFCMDP8JJEI9CZJzruSh4LGSLhALW_ob8yI8',
	송윤호:
		'https://chat.googleapis.com/v1/spaces/AAQAWHU_M-E/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=k0EhAgg9beq1tkJeF76DA3LNH81juhnm2SkL3kAq1vA',
	서강혁:
		'https://chat.googleapis.com/v1/spaces/AAQAbzh00Ig/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=0Yc2qtKPuLa_e-tyYNWPPVHd7O1P2Ujlcq3KYO9ZM3g',
	김일홍:
		'https://chat.googleapis.com/v1/spaces/AAQAsK6CKBs/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=TKC28KE84hn-dzZGkljOMCw6sswcj5WitiNm25bvQRE',
	이지애:
		'https://chat.googleapis.com/v1/spaces/AAQAilk9Ac0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=hE_dV-HGt7y_GQ8mmkwR379yCCOhqysZwG8MyRAd2Fg',
	최기옥:
		'https://chat.googleapis.com/v1/spaces/AAQA1IiIFFk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Bw6skHVx7so4TBSh8_0xhHYIbrdtq4wN64RQW3xgVIc',
	강율이:
		'https://chat.googleapis.com/v1/spaces/AAQAXP-P_V8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=-UhxW6WYT8Llcu2qRfl6WxkTzczZ2lBEh_4Ld8ehzx8',
	황규창:
		'https://chat.googleapis.com/v1/spaces/AAQAnG3V3-0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=K2MnqlhIRKA6ju8qH4oLlCUXrzSTQaN80CoNOIMU1Xo',
	정재선:
		'https://chat.googleapis.com/v1/spaces/AAQAJ1HWlk4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Y7-MfrpMuroPpi-W8d4MJ4KwhSy7BkCumY_kNb4eAyQ',
	노유리:
		'https://chat.googleapis.com/v1/spaces/AAQAldfCCaE/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=d_PRLWAJ3Z2iRxA33_a6l063KQkDx9yMvPfuCVZZEnY',
	정안나:
		'https://chat.googleapis.com/v1/spaces/AAQAakv5Cv4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=oFwQdR5rCuuri1VPGRU_s_Tt6VzpRxyp1wBn0YU819A',
	허지민:
		'https://chat.googleapis.com/v1/spaces/AAQAfSz5IfA/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Qlmo2kNyg4PaLbblUoBz0PXCAak_mfTiJlg5nRQs-BQ',
	정자연:
		'https://chat.googleapis.com/v1/spaces/AAQA1sXIvf0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=QDGoTo_HgQGziozDcQj7ZnJXQeCE8eMSETVQPdYcWik',
	주예진:
		'https://chat.googleapis.com/v1/spaces/AAQABQqyjRM/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=OXnc8yZAFkI9NtdIhVjlU26CDAsfCq-Ssnz99Gtb6yc',
	주지원:
		'https://chat.googleapis.com/v1/spaces/AAQAReG4Sfk/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=-7wR_QB5xJUcXhe9Fyt5Cg2vO6Ch_AuOzJszj51a6PU',
	김기현:
		'https://chat.googleapis.com/v1/spaces/AAQAKnF-uQg/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=9TqwX1PbI1PbVTVvuziq4-ONKl7eyS4h6ikb-owS5Us',
	정예지:
		'https://chat.googleapis.com/v1/spaces/AAQArGhyD2k/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Mi_Oz8-U5ICFFBsGm9Bi4VqrdKStY__yuQAmpRVao2Y',
	이현진:
		'https://chat.googleapis.com/v1/spaces/AAQAEKVHM-E/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=D9wzhXNAW5Xy5mxOkXXqtws2h_yFd2-pHOZiTL432L8',
	이재국:
		'https://chat.googleapis.com/v1/spaces/AAQA-LpPtf4/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=U3B4VLSiPT802BY5JCeCFPoXpsK9B9mLT380OnxKRmQ',
	이윤경:
		'https://chat.googleapis.com/v1/spaces/AAQAtXNN62o/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=Pp2KIfnrc6U7C3hdj8O8MsTB4nJQXtqjXC9K9HX0BIQ',
	최미정:
		'https://chat.googleapis.com/v1/spaces/AAQA-PYadq0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=LDJUMcVDmBuk981XRZtPbwH719Cod7R8fbWTEEIho34',
	이선미:
		'https://chat.googleapis.com/v1/spaces/AAQAqdiXBno/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=0y16mdPhO7ucyPEGFJSzTz4XGRY_dvQ7aOcCVTe33UY',
	유수형:
		'https://chat.googleapis.com/v1/spaces/AAQAIQXxnuc/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=THxSngLPaB7pusbMRVox8xHSd0hJd8aAZ3DP2SPvjt8',
	김지영:
		'https://chat.googleapis.com/v1/spaces/AAQA5t_ye_A/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=b32wmUDrTUrVtAlDCopPnx7GdwbT3dRi5F8yblkysyQ',
	박혜리:
		'https://chat.googleapis.com/v1/spaces/AAQAOIue5R8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=RueC2HnmnMRaN-N35MZa9Oo3EVjlJPkht24hSfN7A8k',
	이경재:
		'https://chat.googleapis.com/v1/spaces/AAQA1STnwjY/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=QQf3FqcqAaD9obu2qX_Q4tED_I068e_6CSHF37Xkl6E',
	이정무:
		'https://chat.googleapis.com/v1/spaces/AAQA4eM3vVU/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=AKm3Tv-yq-ThvBydgesXaWSjGHCUVhjlE8fBkB8P74M',
	김옥배:
		'https://chat.googleapis.com/v1/spaces/AAQAPFCXolY/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=MaMHcBp8kBWyZICPtTHX8vSjq7PFPnlNKtZtUlfmPa8',
	이성운:
		'https://chat.googleapis.com/v1/spaces/AAQAjKBwqIU/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=3a2Y6so27egYbNhjGGEsKr8OQHvd9c_UrrYQOgHvMAY',
	김은희:
		'https://chat.googleapis.com/v1/spaces/AAQAGDlwYqQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=6gbBJN657yDUh791ggpCk4GRDXDl_ybBF3iLOZuVHCg',
	황경진:
		'https://chat.googleapis.com/v1/spaces/AAQAB4tJSxI/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=QjesthAR5YTDmyZtaSuo9j2MexCsMRJSTMEE8O3k9Wo',
	최종훈:
		'https://chat.googleapis.com/v1/spaces/AAQAL4FAbpA/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=a1mrICEPEmoASwTDxSaXSh1ZtM88QhAJG6rB3M04VxY',
	엄인우:
		'https://chat.googleapis.com/v1/spaces/AAQA3XxyH2M/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=6EyNlaQNZiX25PHApv4jZK-BzXmVfhfar9e9HIguu6Y',
	최인영:
		'https://chat.googleapis.com/v1/spaces/AAQA2AsBFYs/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=EU_7j_ajuYjOYGOZzxoLiVvZv42bb5yjuhWOfNHydc8',
	강신완:
		'https://chat.googleapis.com/v1/spaces/AAQASEyqu5g/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=07dWRCZemnLdTZguc73alL1YvSyc9O2y1fYmp1eqHIE'
};
